nodeLinker: node-modules

packageExtensions:
  "@expo/cli@*":
    dependencies:
      expo-modules-autolinking: "*"
  babel-preset-expo@*:
    dependencies:
      "@babel/core": "*"
  expo-asset@*:
    dependencies:
      expo: "*"
  react-native-codegen@*:
    peerDependenciesMeta:
      "@babel/preset-env":
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.4.cjs
